# Generated by Django 5.1.3 on 2025-04-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
